# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

resources:
- ../../wazuh
patches:
- path: storage-class.yaml
- path: indexer-resources.yaml
- path: dashboard-resources.yaml
- path: wazuh-master-resources.yaml
- path: wazuh-worker-resources.yaml
- path: arch.yaml

configMapGenerator:
  - name: wazuh-conf
    behavior: replace
    namespace: wazuh
    files:
      - wazuh_conf/master.conf
#      - wazuh_conf/worker.conf
