# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-dashboard
  namespace: wazuh
spec:
  template:
    spec:
      serviceAccountName: wazuh
      nodeSelector:
        kubernetes.io/arch: amd64

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: wazuh
spec:
  template:
    spec:
      serviceAccountName: wazuh
      nodeSelector:
        kubernetes.io/arch: amd64

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-master
  namespace: wazuh
spec:
  template:
    spec:
      serviceAccountName: wazuh
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: wazuh-filebeat
          configMap:
            name: wazuh-filebeat
        - name: wazuh-local-internal-options
          configMap:
            name: wazuh-local-internal-options
        - name: wazuh-ecr-rules
          configMap:
            name: wazuh-ecr-rules
        - name: wazuh-cxc-rules
          configMap:
            name: wazuh-cxc-rules
        - name: wazuh-cxc-decoder
          configMap:
            name: wazuh-cxc-decoder
      containers:
        - name: wazuh-manager
          volumeMounts:
            - name: wazuh-filebeat
              mountPath: /etc/filebeat/filebeat.yml
              subPath: filebeat.yml
              readOnly: true
            - name: wazuh-local-internal-options
              mountPath: /var/ossec/etc/local_internal_options.conf
              subPath: local_internal_options.conf
              readOnly: true
            - name: wazuh-ecr-rules
              mountPath: /var/ossec/etc/rules/ecr_rules.xml
              subPath: ecr_rules.xml
              readOnly: true
            - name: wazuh-cxc-rules
              mountPath: /var/ossec/etc/rules/cxc_rules.xml
              subPath: cxc_rules.xml
              readOnly: true
            - name: wazuh-cxc-decoder
              mountPath: /var/ossec/etc/decoders/couponxchange.xml
              subPath: couponxchange.xml
              readOnly: true
#            - name: wazuh-authd-pass
#              mountPath: /var/ossec/etc/authd.pass
#              subPath: authd.pass
#              readOnly: true

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker
  namespace: wazuh
spec:
  replicas: 0
  template:
    spec:
      serviceAccountName: wazuh
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: wazuh-filebeat
          configMap:
            name: wazuh-filebeat
      containers:
        - name: wazuh-manager
          volumeMounts:
            - name: wazuh-filebeat
              mountPath: /etc/filebeat/filebeat.yml
              subPath: filebeat.yml
              readOnly: true

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: wazuh-workers
#  namespace: wazuh
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
